import type { ThemeConfig } from 'antd';

const themeConfig: ThemeConfig = {
  token: {
    colorPrimary: '#1E3A8A',
    colorSuccess: '#10B981',
    colorWarning: '#F59E0B',
    colorError: '#EF4444',
    colorInfo: '#0EA5E9',
    colorTextBase: '#1E293B',
    colorBgBase: '#F8FAFC',
    colorBorder: '#E2E8F0',
    colorBgContainer: '#FFFFFF',
    colorBgElevated: '#FFFFFF',
    colorBgLayout: '#F8FAFC',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
    fontSize: 14,
    fontSizeHeading1: 32,
    fontSizeHeading2: 28,
    fontSizeHeading3: 24,
    fontSizeHeading4: 20,
    fontSizeHeading5: 16,
    fontWeightStrong: 600,
    lineHeight: 1.6,
    lineHeightHeading1: 1.2,
    lineHeightHeading2: 1.35,
    lineHeightHeading3: 1.4,
    borderRadius: 6,
    borderRadiusLG: 8,
    borderRadiusSM: 4,
    boxShadow: '0 2px 8px rgba(30, 58, 138, 0.1)',
    boxShadowSecondary: '0 1px 4px rgba(30, 58, 138, 0.08)',
    controlHeight: 36,
    controlHeightLG: 40,
    controlHeightSM: 32,
    motion: true,
    motionUnit: 0.1,
  },
  components: {
    Button: {
      primaryColor: '#1E3A8A',
      controlHeight: 36,
      borderRadius: 6,
      fontWeight: 500,
    },
    Layout: {
      colorBgHeader: '#1E3A8A',
      colorBgBody: '#F8FAFC',
      colorBgTrigger: '#0EA5E9',
    },
    Menu: {
      colorItemBg: '#FFFFFF',
      colorItemBgHover: '#F0F4F8',
      colorItemBgSelected: '#EFF6FF',
      colorItemBgSelectedHorizontal: '#EFF6FF',
      colorDangerItemBgSelected: '#FEE2E2',
      colorPrimaryItemBg: '#EFF6FF',
      colorPrimaryItemBgHover: '#DBEAFE',
      colorPrimaryItemBgSelected: '#DBEAFE',
      colorPrimaryItemBgSelectedHorizontal: '#DBEAFE',
      colorTextLightSolid: '#1E3A8A',
    },
    Card: {
      colorBgContainer: '#FFFFFF',
      boxShadow: '0 1px 4px rgba(30, 58, 138, 0.08)',
      boxShadowSecondary: '0 1px 2px rgba(30, 58, 138, 0.05)',
    },
    Table: {
      colorBgContainer: '#FFFFFF',
      colorBgElevated: '#FAFBFC',
      colorBorder: '#E2E8F0',
      colorText: '#1E293B',
      colorTextHeading: '#1E3A8A',
      colorPrimary: '#0EA5E9',
    },
    Input: {
      colorBgContainer: '#FFFFFF',
      colorBorder: '#E2E8F0',
      colorTextPlaceholder: '#94A3B8',
      controlHeight: 36,
      borderRadius: 6,
    },
    Select: {
      colorBgContainer: '#FFFFFF',
      colorBorder: '#E2E8F0',
      controlHeight: 36,
      borderRadius: 6,
    },
    DatePicker: {
      colorBgContainer: '#FFFFFF',
      colorBorder: '#E2E8F0',
      controlHeight: 36,
      borderRadius: 6,
    },
    Modal: {
      colorBgElevated: '#FFFFFF',
      colorBgMask: 'rgba(0, 0, 0, 0.45)',
      boxShadow: '0 4px 16px rgba(30, 58, 138, 0.15)',
    },
    Drawer: {
      colorBgElevated: '#FFFFFF',
      boxShadow: '-4px 0 16px rgba(30, 58, 138, 0.15)',
    },
    Message: {
      colorSuccess: '#10B981',
      colorWarning: '#F59E0B',
      colorError: '#EF4444',
      colorInfo: '#0EA5E9',
    },
    Tag: {
      colorPrimary: '#0EA5E9',
      colorPrimaryBorder: '#7DD3FC',
      colorSuccess: '#10B981',
      colorWarning: '#F59E0B',
      colorError: '#EF4444',
    },
    Tabs: {
      colorPrimary: '#1E3A8A',
      colorBgContainer: '#FFFFFF',
      colorBorder: '#E2E8F0',
    },
    Checkbox: {
      colorPrimary: '#1E3A8A',
      colorBorder: '#E2E8F0',
    },
    Radio: {
      colorPrimary: '#1E3A8A',
      colorBorder: '#E2E8F0',
    },
    Switch: {
      colorPrimary: '#10B981',
    },
    Progress: {
      colorSuccess: '#10B981',
      colorWarning: '#F59E0B',
    },
    Pagination: {
      colorPrimary: '#1E3A8A',
      colorBgContainer: '#FFFFFF',
    },
  },
};

export default themeConfig;